# The absolute URL to your site. 
# Replace 'username' with your actual GitHub username.
baseURL = 'https://kanna-sr.github.io/'
languageCode = 'en-us'
title = 'VEDA'
theme = 'PaperMod'

# Prevents pathing bugs on case-sensitive Linux hosting (like GitHub Actions)
disablePathToLower = false

[params]
    env = "production"
    description = "Deep dives into GPU internals, NVISA reverse engineering, and hardware security."
    
    # PaperMod specific settings for technical blogs
    defaultTheme = "auto" # Switches between dark/light based on OS preference
    ShowToc = true        # Automatically display Table of Contents on posts
    TocOpen = true        # Keep TOC open by default on desktop layouts

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 10
    [[menu.main]]
        name = "NVIDIA"
        url = "/content/posts/gpu_arch/"
        weight = 15
    [[menu.main]]
        name = "Vouchers"
        url = "/content/posts/vouchers/"
        weight = 14

# Minifies HTML, CSS, and JS to make your static site load blazingly fast
[minify]
    minifyOutput = true
